export const FETCH_CLINICIAN_EXPERIENCES_REQUEST = Symbol('FETCH_CLINICIAN_EXPERIENCES_REQUEST')
export const FETCH_CLINICIAN_EXPERIENCES_SUCCESS = Symbol('FETCH_CLINICIAN_EXPERIENCES_SUCCESS')
export const FETCH_CLINICIAN_EXPERIENCES_FAILURE = Symbol('FETCH_CLINICIAN_EXPERIENCES_FAILURE')

export const UPDATE_CLINICIAN_EXPERIENCES_REQUEST = Symbol('UPDATE_CLINICIAN_EXPERIENCES_REQUEST')
export const UPDATE_CLINICIAN_EXPERIENCES_SUCCESS = Symbol('UPDATE_CLINICIAN_EXPERIENCES_SUCCESS')
export const UPDATE_CLINICIAN_EXPERIENCES_FAILURE = Symbol('UPDATE_CLINICIAN_EXPERIENCES_FAILURE')
