export const FETCH_DOCUMENTS_REQUEST = Symbol('FETCH_DOCUMENTS_REQUEST')
export const FETCH_DOCUMENTS_SUCCESS = Symbol('FETCH_DOCUMENTS_SUCCESS')
export const FETCH_DOCUMENTS_FAILURE = Symbol('FETCH_DOCUMENTS_FAILURE')

export const EDIT_DOCUMENTS_REQUEST = Symbol('EDIT_DOCUMENTS_REQUEST')
export const EDIT_DOCUMENTS_SUCCESS = Symbol('EDIT_DOCUMENTS_SUCCESS')
export const EDIT_DOCUMENTS_FAILURE = Symbol('EDIT_DOCUMENTS_FAILURE')
