export const FETCH_EXPERIENCES_REQUEST = Symbol('FETCH_EXPERIENCES_REQUEST')
export const FETCH_EXPERIENCES_SUCCESS = Symbol('FETCH_EXPERIENCES_SUCCESS')
export const FETCH_EXPERIENCES_FAILURE = Symbol('FETCH_EXPERIENCES_FAILURE')
