export const CREATE_CLINICIAN_TOKEN_REQUEST = Symbol('CREATE_CLINICIAN_TOKEN_REQUEST')
export const CREATE_CLINICIAN_TOKEN_SUCCESS = Symbol('CREATE_CLINICIAN_TOKEN_SUCCESS')
export const CREATE_CLINICIAN_TOKEN_FAILURE = Symbol('CREATE_CLINICIAN_TOKEN_FAILURE')
export const CLEAR_CLINICIAN_TOKEN_ERROR = Symbol('CLEAR_CLINICIAN_TOKEN_ERROR')
