export const CREATE_PROVIDER_REQUEST = Symbol('CREATE_PROVIDER_REQUEST')
export const CREATE_PROVIDER_SUCCESS = Symbol('CREATE_PROVIDER_SUCCESS')
export const CREATE_PROVIDER_FAILURE = Symbol('CREATE_PROVIDER_FAILURE')
