export const CREATE_PROVIDER_TOKEN_REQUEST = Symbol('CREATE_PROVIDER_TOKEN_REQUEST')
export const CREATE_PROVIDER_TOKEN_SUCCESS = Symbol('CREATE_PROVIDER_TOKEN_SUCCESS')
export const CREATE_PROVIDER_TOKEN_FAILURE = Symbol('CREATE_PROVIDER_TOKEN_FAILURE')
