export const CREATE_CLINICIAN_REQUEST = Symbol('CREATE_CLINICIAN_REQUEST')
export const CREATE_CLINICIAN_SUCCESS = Symbol('CREATE_CLINICIAN_SUCCESS')
export const CREATE_CLINICIAN_FAILURE = Symbol('CREATE_CLINICIAN_FAILURE')

export const EDIT_CLINICIAN_REQUEST = Symbol('EDIT_CLINICIAN_REQUEST')
export const EDIT_CLINICIAN_SUCCESS = Symbol('EDIT_CLINICIAN_SUCCESS')
export const EDIT_CLINICIAN_FAILURE = Symbol('EDIT_CLINICIAN_FAILURE')

export const FETCH_CURRENT_CLINICIAN_REQUEST = Symbol('FETCH_CURRENT_CLINICIAN_REQUEST')
export const FETCH_CURRENT_CLINICIAN_SUCCESS = Symbol('FETCH_CURRENT_CLINICIAN_SUCCESS')
export const FETCH_CURRENT_CLINICIAN_FAILURE = Symbol('FETCH_CLINICIAN_FAILURE')
